export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB';
export const UPDATE_BREADCRUMB_SUCCESS = 'UPDATE_BREADCRUMB_SUCCESS';

export const ACTIVE_CONTENT = "ACTIVE_CONTENT";
export const ACTIVE_CONTENT_SUCCESS = "ACTIVE_CONTENT_SUCCESS";

export const ACTIVE_MENU_CONTENT = "ACTIVE_MENU_CONTENT";
export const ACTIVE_MENU_CONTENT_SUCCESS = "ACTIVE_MENU_CONTENT_SUCCESS";

export const ALL_SEGMENTS = "ALL_SEGMENTS";
export const ALL_SEGMENTS_SUCCESS = "ALL_SEGMENTS_SUCCESS";