export const UPDATE_BREADCRUMB = 'UPDATE_BREADCRUMB';
export const UPDATE_BREADCRUMB_SUCCESS = 'UPDATE_BREADCRUMB_SUCCESS';

export const ACTIVE_CONTENT = "ACTIVE_CONTENT";
export const ACTIVE_CONTENT_SUCCESS = "ACTIVE_CONTENT_SUCCESS";

export const ACTIVE_MENU_CONTENT = "ACTIVE_MENU_CONTENT";
export const ACTIVE_MENU_CONTENT_SUCCESS = "ACTIVE_MENU_CONTENT_SUCCESS";

export const ALL_SEGMENTS = "ALL_SEGMENTS";
export const ALL_SEGMENTS_SUCCESS = "ALL_SEGMENTS_SUCCESS";

export const NODE_TYPE = "NODE_TYPE";
export const NODE_TYPE_SUCCESS = "NODE_TYPE_SUCCESS";

export const USER_ROLE = "USER_ROLE";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";

export const COLLAPSE_SIDEBAR = "COLLAPSE_SIDEBAR";
export const COLLAPSE_SIDEBAR_SUCCESS = "COLLAPSE_SIDEBAR_SUCCESS";
